### ISSUE TITLE
3.0 Is it considered to remove the `yii2-` prefix?

### ISSUE THREAD

**Issue by kids-return** [yiisoft/core#1]
3.0 is compatible with 2.0 extensions
Does the official old 2.0 extension consider removing prefixes like yii2-debug, yii2-queue, yii2-httpclient
Does the new extension official recommend the `yii2-` prefix?
I am currently designing an application based on `yii2` and consider giving up the 2.0 version, but I have a lot of old extensions that use the `yii2-` prefix.
For 3.0 I can now refactor to remove the `yii2-` prefix?

**Comment by hiqsol** [comment]
Thank you for you question.
It's very important topic.
The question will be thought over thoroughly.
You'll get answers soon.

**Comment by hiqsol** [comment]
It is planned to recommend having `yii-` prefix. Without number.
Version compatibility will be specified in composer.json require section constraints.

Also if you plan your extension to be usable without yii you should name it without prefix.
