### ISSUE TITLE
Create a repo for routing related

### ISSUE THREAD

**Issue by kids-return** [yiisoft/core#10]
move `\yii\web\UrlRule`  to `\yii\route\UrlRule`  
move `\yii\web\GroupUrlRule`  to `\yii\route\GroupUrlRule`

`yii-web` require `yii-route`
`yii-rest` require `yii-route`

**Comment by samdark** [comment]
There's no interface extracted for routing yet and it's not an easy thing to plan for. I'd postpone it till Yii 4.0.
