### ISSUE TITLE
Why are only some yiisoft repos are prefixed with yii-?

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/core#12]
Why are some `yiisoft` repos are prefixed with `yii-` like `yii-web` or `yii-console` and others not, like `db` and `cache`?

See also https://github.com/yiisoft/yii-app/issues/40#issuecomment-414984441

**Comment by hiqsol** [comment]
Please see:

- https://github.com/yiisoft/docs/blob/master/packages.md
- https://github.com/yiisoft/yii-app/issues/40#issuecomment-415019852
