### ISSUE TITLE
Why is hiqdev/composer-config-plugin a dev-dependency?

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/core#13]
Why is hiqdev/composer-config-plugin a dev-dependency?

From my understanding it is used to generate configs for applications (-templates), but why is it in the core?

**Comment by hiqsol** [comment]
It is used to assemble configuration for tests.

**Comment by schmunk42** [comment]
Does it need to be run before running tests (like described in https://github.com/yiisoft/core/tree/master/tests)? Sorry, haven't testing it yet.
